# Generated by Django 4.0.4 on 2024-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='lesson',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
