# Generated by Django 4.0.4 on 2024-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messages_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='lesson',
            field=models.CharField(default='te', max_length=50),
            preserve_default=False,
        ),
    ]
