# Generated by Django 4.0.4 on 2024-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messages_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='data', max_length=500),
            preserve_default=False,
        ),
    ]
